name: Build Android APK

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build universal APK
        run: flet build apk --yes --force

      - name: Save Universal APK
        run: |
          BUILD_DATE=$(date +'%Y-%m-%d')
          BUILD_NUM="${{ github.run_number }}"
          mkdir -p release_apk

          cp build/apk/*.apk "release_apk/ModuFlexGUI-universal-b${BUILD_NUM}_${BUILD_DATE}.apk"

      - name: Build Split APKs
        run: flet build apk --yes --split-per-abi --force

      - name: Save Split APKs
        run: |
          BUILD_DATE=$(date +'%Y-%m-%d')
          BUILD_NUM="${{ github.run_number }}"

          for apk in build/apk/*.apk; do
            filename=$(basename "$apk")
            cp "$apk" "release_apk/${filename}-b${BUILD_NUM}_${BUILD_DATE}"
          done

      - name: Upload APKs to created Release
        uses: softprops/action-gh-release@v2
        with:
          files: release_apk/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
